server:
  port: ${SERVER_PORT:9005}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:ow_orders_db}
# **TODO**
# Add the properties required by the KafkaConfig class here.
# Below properties are used by the KafkaConfig class.
#   kafka.bootstrap-servers
#   kafka.topic-name
#  Add them as environment variables with default values corresponding to local installation
kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  topic-name: ${KAFKA_TOPIC:customer_orders}