server:
  port: ${SERVER_PORT:9010}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:ow_customers_db}
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:ow_users_db}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
jwt:
  secret: confidential

# **TODO**
# Add the properties required by the KafkaConfig class here.
# Below properties are used by the KafkaConfig class.
#   kafka.bootstrap-servers
#   kafka.topic-name
#  Add them as environment variables with default values corresponding to local installation
kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
  topic-name: ${KAFKA_TOPIC:customer_orders}